name: ms-ifawebapp
dependencies:
  - python==3.12.*
  - conda==23.11.*
  - pip==24.0.*
  - pip:
    - flask==3.0.*
    - flask-login==0.6.*
    - flask-mysqldb==2.0.*
    - flask-wtf==1.2.*
    - email-validator==2.1.*
    - flask-migrate==4.0.*