"""empty message

Revision ID: 0d24dbef1cb9
Revises: cecdefc9d696
Create Date: 2024-02-29 20:58:36.802101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d24dbef1cb9'
down_revision = 'cecdefc9d696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basevalue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymodes', schema=None) as batch_op:
        batch_op.drop_column('basevalue')

    # ### end Alembic commands ###
