"""empty message

Revision ID: 89a72beb1801
Revises: b51e857bb4bf
Create Date: 2024-02-14 21:13:29.500616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89a72beb1801'
down_revision = 'b51e857bb4bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=True))
        batch_op.drop_column('firsname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firsname', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
