"""empty message

Revision ID: 8e0dd7a660cf
Revises: b838763fade0
Create Date: 2024-02-17 14:17:38.449321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0dd7a660cf'
down_revision = 'b838763fade0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveyanswers', schema=None) as batch_op:
        batch_op.drop_constraint('surveyanswers_ibfk_3', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveyanswers', schema=None) as batch_op:
        batch_op.create_foreign_key('surveyanswers_ibfk_3', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
