"""empty message

Revision ID: b838763fade0
Revises: 89a72beb1801
Create Date: 2024-02-15 17:55:51.011504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b838763fade0'
down_revision = '89a72beb1801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveyanswers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('surveyanswers_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'surveys', ['survey_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('surves_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveyanswers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surves_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('surveyanswers_ibfk_2', 'surveys', ['surves_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('survey_id')

    # ### end Alembic commands ###
