"""empty message

Revision ID: e0bd2c7ab457
Revises: 0d24dbef1cb9
Create Date: 2024-02-29 21:33:45.865670

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0bd2c7ab457'
down_revision = '0d24dbef1cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial', sa.Boolean(), nullable=True))
        batch_op.drop_column('basevalue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveymodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basevalue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('initial')

    # ### end Alembic commands ###
